### ISSUE TITLE
Skip Abominations button

### ISSUE THREAD

**Issue by CGR99** [mylaaan/FtHoF-Planner-v4#5]
It seems the Skip Abominations button is doing the exact opposite of what's intended.
It's easy enough to work around, of course, but I just wanted to mention it.
The quick fix would be to change the label, but then it would still work opposite of how the Skip Spontaneous Edifices button works.

**Comment by mylaaan** [comment]
Get you elaborate a bit more. Because this "skipping" is only related to the combo planner. If you select Skip Abominations/Edifice the counter on the "spread" of the combo goes down.
The idea is that (because most of the time you will have elder pledge active because you want golden cookies instead of wrath cookies) that you can use it to advance one spell without lossing any mana. So if you select them to skip them the combo-planner can reduce the spread of a combo because you can advance a spell for free.
If this still somehow isn't in line with your thinking I would gladly hear about to explain further.

**Comment by CGR99** [comment]
That clears up the issue. I apologize - it was my misunderstanding.

**Comment by mylaaan** [comment]
No problem!

**Comment by CGR99** [comment]
Quick side question, is there a reason one of the Spontaneous Edifice is shaded in blue, but the other isn't? Both Resurrect Abomination are shaded blue.

**Comment by mylaaan** [comment]
The positive ones only give you a building extra if there is a building you have less than 400 of them. So if you have more you skip the spell. The negative one will take a building away which you will always have.
