### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AEE3H** [mylaaan/FtHoF-Planner-v4#7]
Doesent work anymore got broken by new update

**Comment by mylaaan** [comment]
This isn't very helpful, Like I said in the post about making a bug report tell exactly what is broken en post your export code. With this information I can't do anything. For me and many others it works.
If you are seeing Cookie storm drop and think it doesn't work is because it's not a cookie storm. Cookie storm drop is just as if you clicked a single cookie in a cookie storm. It looks like lucky but it isn't. it's worth waaaay less.
If that's not the case please check if all parameters are check according to your own game situation.

I'm gonna close this. If you have an actual bug please open another report with details and an export code so I can replicate the problem you are having so I can fix it.
